apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment #name of object created by this file
spec:
  replicas: 5
  selector:
    matchLabels:
      component: web
  template: # config for every single pod that will be created
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client # ability to reference this container
          image: stephengrider/multi-worker
          ports:
            - containerPort: 8888


