apiVersion: v1
kind: Pod # kind represents type of object we want to make
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client # ability to reference this container
      image: stephengrider/multi-worker
      ports:
        - containerPort: 9999 # expose 3000 to outside world
