use testsql;
CREATE TABLE EMPLOYEE (
 ID 						INT  NOT NULL AUTO_INCREMENT,
 FNAME               VARCHAR(15) NOT NULL,
 LNAME               VARCHAR(15) NOT NULL,
 SSN                 CHAR(9) NOT NULL,
 SALARY              DECIMAL(10,2),
 SUPERSSN            CHAR(9),
 DNO                 INT NOT NULL,
 PRIMARY KEY (ID)
 ) ENGINE = InnoDB
AUTO_INCREMENT = 1;

CREATE TABLE DEPARTMENT (
DNUMBER INT ZEROFILL NOT NULL AUTO_INCREMENT REFERENCES EMPLOYEE(ID),
 DNAME               VARCHAR(15) NOT NULL,
  MGRSSN              CHAR(9),
 MGRSTARTDATE        DATE,
  PRIMARY KEY (DNUMBER)
 ) ENGINE = InnoDB
AUTO_INCREMENT = 1;


INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Lars','Monsen', '3985095', 75000, null, 1);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Rest','Monsen', '894809',  55000, null, 2);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Jhan','Gretyjs', '9856789', 23000, null, 3);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Great', 'Tahdkjd', '7980022', 81020, null, 2);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Tesndiki', 'Ragsnjs', '0847839', 30241 , null, 2);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Elias', 'Reajns', '9892292',  56000, null, 3);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Stas', 'Halks', '34242',  43000, null, 1);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Jhakjs', 'Minut', '2754443', 60210 , null, 1);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Jlkalk', 'Ulalks', '774534',  62060, null, 2);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Diclksa', 'Kslls', '96755',  63500, null, 5);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Tjhkaj', 'Uoadj', '9802903',  68000, null, 4);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Reths', 'Grauij', '09948242',  75000, null, 2);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('Greg', 'manto', '98932',  36000, null, 1);
INSERT INTO EMPLOYEE (FNAME,LNAME, SSN, SALARY, SUPERSSN, DNO) VALUES ('JIjdowkd', 'owds', '8924802', 75012, null, 2);




INSERT INTO DEPARTMENT (DNAME,MGRSSN, MGRSTARTDATE) VALUES ('Digital', '3985095', CURDATE());
INSERT INTO DEPARTMENT (DNAME,MGRSSN, MGRSTARTDATE) VALUES ('Retail', '0847839', CURDATE()-2);
INSERT INTO DEPARTMENT (DNAME,MGRSSN, MGRSTARTDATE) VALUES ('Customer', '9892292', CURDATE()-5);
INSERT INTO DEPARTMENT (DNAME,MGRSSN, MGRSTARTDATE) VALUES ('BI', '6589245', CURDATE()-4);
INSERT INTO DEPARTMENT (DNAME,MGRSSN, MGRSTARTDATE) VALUES ('Infra', '7854236', CURDATE()-3);
select * from DEPARTMENT;

desc EMPLOYEE;
desc DEPARTMENT;